# Generated by Django 5.2.1 on 2025-06-01 15:46

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "_id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("done", models.BooleanField(default=False)), # type: ignore
                ("userId", django_mongodb_backend.fields.ObjectIdField()),
            ],
        ),
    ]
